server:
  name: globetrotter
  port: 8080

database:
  type: postgres
  postgres:
    host: "localhost"
    port: 5432
    username: "user"
    password: "password"
    dbName: "globetrotter"
    schema: "globetrotter"